### PR TITLE
Upgrade to new LTS Spring-Boot 3.2.x and Camel 4.4.x

### PR DESCRIPTION
**Pull request by graben**

### CODE REVIEW

**Comment by graben** [comment]
Hi @geoand,
could you please merge and organize a minor release is getting done soon? Unfortunately, @jacobdotcosta does not react on any of my last requests.
Thanks, Benjamin

FYI @cunningt: Getting master in sync with jboss-fuse fork, again. ;)

**Review by geoand — APPROVED** [review]

**Comment by graben** [comment]
One week later and nothing happens. Hmm...

**Comment by jacobdotcosta** [comment]
I'll do the release now.

**Comment by jacobdotcosta** [comment]
I've released `3.1.0.Beta1`, could anyone take a look at it before I do the `Final` release? Not in Maven Central yet though.

**Comment by graben** [comment]
Hi @jacobdotcosta,

thx for doing the release. Actually, I see that `<tag>3.1.0.Beta1</tag>` in parent pom is not switched back to `HEAD` after release. Anyway, I could successfully checkout and build tag 3.1.0.Beta1 and do a quick test.

Best regards
Benjamin

**Comment by jacobdotcosta** [comment]
Thank you @graben . I've fixed the tag and will make the definitive release.

**Comment by graben** [comment]
@jacobdotcosta don't forget to patch samples manually after release. Those poms are not affected by maven-release-plugin!

**Pull request merged**
