### PR TITLE
Generate right-length nodeIdentifier/ XID

### PR DESCRIPTION
**Pull request by graben**
resolve #132

@geoand: This one is squashed and rebased ;)

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by graben** [comment]
@geoand: Is there still something missing, preventing merge?

**Comment by geoand** [comment]
What's make you say that?

**Comment by graben** [comment]
@geoand : Would it be possible to trigger someone, e.g. @jacobdotcosta to do a 3.0.1 release soon? Thanks, Benjamin

**Comment by geoand** [comment]
As you said, up to @jacobdotcosta :)

**Pull request merged**
