### PR TITLE
Cast JtaTransactionManager to org.springframework.transaction.TransactionManager while calling TransactionManagerCustomizers.customize because method to be removed in Spring Boot 3.4.0

### PR DESCRIPTION
**Pull request by graben**
Hi @geoand, can you please merge.
Thx Benjamin

### CODE REVIEW

**Comment by geoand** [comment]
Hi,

What's the reason for doing this casting?

**Comment by graben** [comment]
Spring Boot 3.2 has introduced an overloaded `customize `method `TransactionManagerCustomizers `for `org.springframework.transaction.TransactionManager` and marked for removal the old `org.springframework.transaction.PlatformTransactionManager` one. This method is now removed in Spring Boot 3.4 but compilation in narayana-spring-boot-starter 3.3.0 has been done against exactly this one causing Exceptions on startup.

**Comment by geoand** [comment]
Gotcha, thanks

**Review by geoand — APPROVED** [review]

**Comment by graben** [comment]
Hi @jacobdotcosta,

can you please plan a 3.3.1 bugfix release?

Regards Benjamin

**Comment by jacobdotcosta** [comment]
Yes, I'll do the release.

**Comment by jacobdotcosta** [comment]
`3.3.1.Beta1` has been released. @graben, could you please take a look at it.

**Comment by graben** [comment]
Hi @jacobdotcosta, will do it this evening CET. Thanks Benjamin

**Comment by graben** [comment]
@jacobdotcosta: Build and tested successfully. Go ahead with the release ;)

**Comment by jacobdotcosta** [comment]
`3.3.1` released

**Pull request merged**
