### PR TITLE
Revert "Generate right-length nodeIdentifier/ XID"

### PR DESCRIPTION
**Pull request by graben**
Solves #140

Update to #132/#136/quarkusio/quarkus#30491

### CODE REVIEW

**Comment by graben** [comment]
For MariaDB I can confirm that the shorten nodename is causing an issue in command `XA START`. Generated HEX String is too long > 64 characters.

@geoand: Maybe hashing approach has drawback also for Quarkus. Should be verified!

**Comment by geoand** [comment]
So if I understand correctly, you are changing the default behavior to not shorten the ID? Why this change of default (which is a breaking change)?

**Comment by graben** [comment]
This feature was introduced in the last version 3.1.0 as a back port from Quarkus where it is disabled by default. So I do just add what should be there already. But it seems that this feature has drawbacks anyway in Spring boot and Quarkus which should be evaluated. 😉

**Comment by geoand** [comment]
Understood, thanks

**Comment by graben** [comment]
Well, It seems the patch at Quarkus is wrong. SHA-224 creates a 28 sized byte array but after creating a UTF-8 String from it the corresponding byte array is somewhere around size 40-60 much bigger than 28 :-/

**Comment by geoand** [comment]
Thanks for investigating.

Please open a relevant issue in the Quarkus repo

**Comment by graben** [comment]
In the meantime I would suggest to revert this feature for a 3.1.1 patch release until a better fix is found.

@geoand : okay for you?

**Comment by geoand** [comment]
Sounds good to me

**Comment by graben** [comment]
@geoand : Revert #136 as discussed.
@jacobdotcosta: Could you plz do a 3.1.1 patch release after merge?

**Review by geoand — APPROVED** [review]

**Comment by jacobdotcosta** [comment]
I'll release 3.1.1.

**Comment by graben** [comment]
Looks good to me, but could really test it tomorrow, okay for you?

**Comment by graben** [comment]
@jacobdotcosta: build and tested successfully. Ready to release! ;-)

**Comment by graben** [comment]
@jacobdotcosta thx, but don't miss the scm tag 😉

**Comment by jacobdotcosta** [comment]
fixed :(

**Pull request merged**
