### PR TITLE
Update Narayana to 7.0.2.Final

### PR DESCRIPTION
**Pull request by graben**
Dependent on #149, agroal/agroal#109

### CODE REVIEW

**Comment by graben** [comment]
@marcosgopen: Trying to update to Narayana 7.0.2.Final causing tests to fail. There might be an issue to address before official announce?

**Comment by marcosgopen** [comment]
Thanks @graben for letting me know. I will have a look.

**Comment by graben** [comment]
> Thanks @graben for letting me know. I will have a look.

Give me a hint if I can help!

**Comment by marcosgopen** [comment]
> > Thanks @graben for letting me know. I will have a look.
> 
> Give me a hint if I can help!

TBF we are not encountering a failure in our regression tests, so this is very interesting. The change that affected your test is https://github.com/jbosstm/narayana/pull/2246, but still we are working to find out why. I will keep you updated.

**Comment by graben** [comment]
Well, it seems that an early called recover(XAResource.TMENDRSCAN) does cause a disconnect of the internal used JDBC connection. (https://github.com/snowdrop/narayana-spring-boot/blob/2d94a3e72fa78b9f5d78f73b6c961cb8803cfe07/narayana-spring-boot-core/src/main/java/dev/snowdrop/boot/narayana/core/jdbc/DataSourceXAResourceRecoveryHelper.java#L112)

Btw. Agroal unit test does fail, too also used here for pooling integration

FYI @barreiro

**Comment by graben** [comment]
Maybe `DataSourceXAResourceRecoveryHelper` needs to be refit for 7.0.2. Not really nice for a patch update of a dependency :/

**Comment by graben** [comment]
Oh, I'm sorry for that. Maybe the patch could be reused for a major version upgrade again?

**Comment by marcosgopen** [comment]
After updating Narayana PooledTransactionalIT test fails with 7.0.2.Final: ''[ERROR] Errors:
[ERROR] PooledRecoveryIT>GenericRecoveryIT.testCrashBeforeCommit:122 » ConditionTimeout Condition with alias 'Wait for the recovery to happen' didn't complete within 1 minutes because assertion condition with alias Wait for the recovery to happen [Test entry should exist after transaction was committed]
Expected size: 1 but was: 0 in:
[]."

That is because of another issue [Review JTS and JTA way to handle RMFAIL in xa_rollback](https://issues.redhat.com/browse/JBTM-3838). In fact now Narayana is not treating XAER_RMFAIL as a transient failure and would consider it a heuristic aligning to xa_rollback specification (https://publications.opengroup.org/c193)

From the test log you can read: "WARN 170836 --- [nsaction Reaper] com.arjuna.ats.arjuna : ARJUNA012117: TransactionReaper::check processing TX 0:ffffc0a82b22:a64d:66840d2a:1e in state RUN"

This is a issue that might have already been solved by Artemis team (maybe https://github.com/apache/activemq-artemis/commit/269be13c5a). FYI @graben

**Comment by graben** [comment]
@geoand : Now this one is ready ;)

**Review by geoand — APPROVED** [review]

**Pull request merged**
