### PR TITLE
Update Spring boot to 3.2.8

### PR DESCRIPTION
**Pull request by graben**

### CODE REVIEW

**Comment by graben** [comment]
@geoand : Last PR before releasing 3.2.0

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Thanks!

**Comment by graben** [comment]
@jacobdotcosta : Could you please plan a 3.2.0 release from master. Thanks!

**Comment by jacobdotcosta** [comment]
Hi! Yes, I'll take care of this.

**Comment by jacobdotcosta** [comment]
Done. 3.2.0 is released.
FYI @graben

**Comment by graben** [comment]
Well, commit history looks weird. Missing maven release plugin commits especially for tag!

**Comment by jacobdotcosta** [comment]
Not sure what happened. The release process ended OK but the artifacts aren't on sonatype.

**Comment by graben** [comment]
I would suggest to reset main to the last real commit. And start release once again.

**Comment by jacobdotcosta** [comment]
I've release `3.2.0.Beta1`. It's on Nexus. Could you take a look at it @graben ?

**Comment by graben** [comment]
@jacobdotcosta: Successfully build from tag and tested artifact from Maven Central.

**Comment by jacobdotcosta** [comment]
Will do the `3.2.0` release now. 🤞🏽

**Comment by jacobdotcosta** [comment]
Release failed as there's an outage on `oss.sonatype.org` - https://status.maven.org/

**Comment by graben** [comment]
@jacobdotcosta: OSSRH seems to be up again.

**Comment by jacobdotcosta** [comment]
3.2.0 has been released
FYO @graben

**Pull request merged**
