### PR TITLE
Bump openshift-client to 6.9.2

### PR DESCRIPTION
**Pull request by graben**

### CODE REVIEW

**Comment by graben** [comment]
Hi @cunningt, can plz review?

**Review by cunningt — APPROVED** [review]
Looks good to me!

**Comment by cmoulliard** [comment]
Can you fix the conflict please ? @graben

**Comment by graben** [comment]
@cmoulliard : Rebased PR

**Comment by graben** [comment]
@cmoulliard : still something missing for merge?

**Pull request merged**
