### PR TITLE
Update Camel to 4.8.1

### PR DESCRIPTION
**Pull request by graben**

### CODE REVIEW

**Comment by graben** [comment]
@geoand: Could you please merge?

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
This needs a rebase

**Comment by graben** [comment]
@geoand: Rebase done

**Review by geoand — APPROVED** [review]

**Comment by graben** [comment]
Hi @jacobdotcosta,
can you make a 3.3 release soon from main branch?
Thanks, Benjamin

**Comment by graben** [comment]
Hi @jacobdotcosta,

any feedback on doing a release?

Regards Benjamin

**Comment by jacobdotcosta** [comment]
I'll do the release today.

**Comment by graben** [comment]
@jacobdotcosta: Ping me when I should test a beta.

**Comment by jacobdotcosta** [comment]
@graben : 3.3.0.Beta1 has been released

**Comment by graben** [comment]
@jacobdotcosta: Build and tested successfully!

**Comment by jacobdotcosta** [comment]
FYI @graben 3.3.0 has been released.

**Pull request merged**
