### PR TITLE
Update Agroal to 2.4

### PR DESCRIPTION
**Pull request by graben**
@barreiro: Maybe a regression in latest Agroal version? I'll have a look into the test case either way.

### CODE REVIEW

**Comment by barreiro** [comment]
@graben maybe, although the `Closing open connection(s) prior to commit` are a bit suspicious. maybe the pool size for the test needs to be increased ??

**Comment by graben** [comment]
I'm actually thinking it could be something like timing between parallel threads. But this is currently only a hypothesis.

**Comment by graben** [comment]
@barreiro : Setting the wait timeout to a larger value helps, but it needs closing the complete pool of 10 Connections? I think something is going wrong.

```
2024-05-23T18:31:58.560+02:00  INFO 20632 --- [riodic Recovery] d.s.boot.narayana.utils.BytemanHelper    : dev.snowdrop.boot.narayana.utils.BytemanHelper increment commits counter: 2
2024-05-23T18:31:58.580+02:00  INFO 20632 --- [ntContainer#0-1] d.s.boot.narayana.app.MessagesService    : Received message 'test-message'
2024-05-23T18:31:59.540+02:00  INFO 20632 --- [very to happen]] d.s.boot.narayana.app.MessagesService    : Returning received messages '[test-message]'
2024-05-23T18:31:59.543+02:00  WARN 20632 --- [very to happen]] io.agroal.api.AgroalDataSource.'jdbc'    : Closing open connection(s) prior to commit
2024-05-23T18:31:59.548+02:00  INFO 20632 --- [very to happen]] d.s.boot.narayana.app.EntriesService     : Returning entries '[]'
2024-05-23T18:32:00.561+02:00  INFO 20632 --- [very to happen]] d.s.boot.narayana.app.MessagesService    : Returning received messages '[test-message]'
2024-05-23T18:32:00.567+02:00  WARN 20632 --- [very to happen]] io.agroal.api.AgroalDataSource.'jdbc'    : Closing open connection(s) prior to commit
2024-05-23T18:32:00.569+02:00  INFO 20632 --- [very to happen]] d.s.boot.narayana.app.EntriesService     : Returning entries '[]'
2024-05-23T18:32:01.582+02:00  INFO 20632 --- [very to happen]] d.s.boot.narayana.app.MessagesService    : Returning received messages '[test-message]'
2024-05-23T18:32:01.587+02:00  WARN 20632 --- [very to happen]] io.agroal.api.AgroalDataSource.'jdbc'    : Closing open connection(s) prior to commit
2024-05-23T18:32:01.588+02:00  INFO 20632 --- [very to happen]] d.s.boot.narayana.app.EntriesService     : Returning entries '[]'
2024-05-23T18:32:02.599+02:00  INFO 20632 --- [very to happen]] d.s.boot.narayana.app.MessagesService    : Returning received messages '[test-message]'
2024-05-23T18:32:02.605+02:00  WARN 20632 --- [very to happen]] io.agroal.api.AgroalDataSource.'jdbc'    : Closing open connection(s) prior to commit
2024-05-23T18:32:02.606+02:00  INFO 20632 --- [very to happen]] d.s.boot.narayana.app.EntriesService     : Returning entries '[]'
2024-05-23T18:32:03.619+02:00  INFO 20632 --- [very to happen]] d.s.boot.narayana.app.MessagesService    : Returning received messages '[test-message]'
2024-05-23T18:32:03.625+02:00  WARN 20632 --- [very to happen]] io.agroal.api.AgroalDataSource.'jdbc'    : Closing open connection(s) prior to commit
2024-05-23T18:32:03.625+02:00  INFO 20632 --- [very to happen]] d.s.boot.narayana.app.EntriesService     : Returning entries '[]'
2024-05-23T18:32:04.641+02:00  INFO 20632 --- [very to happen]] d.s.boot.narayana.app.MessagesService    : Returning received messages '[test-message]'
2024-05-23T18:32:04.646+02:00  WARN 20632 --- [very to happen]] io.agroal.api.AgroalDataSource.'jdbc'    : Closing open connection(s) prior to commit
2024-05-23T18:32:04.647+02:00  INFO 20632 --- [very to happen]] d.s.boot.narayana.app.EntriesService     : Returning entries '[]'
2024-05-23T18:32:05.651+02:00  INFO 20632 --- [very to happen]] d.s.boot.narayana.app.MessagesService    : Returning received messages '[test-message]'
2024-05-23T18:32:05.656+02:00  WARN 20632 --- [very to happen]] io.agroal.api.AgroalDataSource.'jdbc'    : Closing open connection(s) prior to commit
2024-05-23T18:32:05.656+02:00  INFO 20632 --- [very to happen]] d.s.boot.narayana.app.EntriesService     : Returning entries '[]'
2024-05-23T18:32:06.670+02:00  INFO 20632 --- [very to happen]] d.s.boot.narayana.app.MessagesService    : Returning received messages '[test-message]'
2024-05-23T18:32:06.674+02:00  WARN 20632 --- [very to happen]] io.agroal.api.AgroalDataSource.'jdbc'    : Closing open connection(s) prior to commit
2024-05-23T18:32:06.675+02:00  INFO 20632 --- [very to happen]] d.s.boot.narayana.app.EntriesService     : Returning entries '[]'
2024-05-23T18:32:07.686+02:00  INFO 20632 --- [very to happen]] d.s.boot.narayana.app.MessagesService    : Returning received messages '[test-message]'
2024-05-23T18:32:07.691+02:00  WARN 20632 --- [very to happen]] io.agroal.api.AgroalDataSource.'jdbc'    : Closing open connection(s) prior to commit
2024-05-23T18:32:07.692+02:00  INFO 20632 --- [very to happen]] d.s.boot.narayana.app.EntriesService     : Returning entries '[]'
2024-05-23T18:32:08.693+02:00  INFO 20632 --- [very to happen]] d.s.boot.narayana.app.MessagesService    : Returning received messages '[test-message]'
2024-05-23T18:32:08.708+02:00  WARN 20632 --- [very to happen]] io.agroal.api.AgroalDataSource.'jdbc'    : Closing open connection(s) prior to commit
2024-05-23T18:32:08.709+02:00  INFO 20632 --- [very to happen]] d.s.boot.narayana.app.EntriesService     : Returning entries '[Entry{id=1, value='test-value'}]'
```

**Comment by barreiro** [comment]
that message means that the connection wrappers are still open on commit and Agroal is closing them for you (to prevent concurrent calls with commit, and eventual leaks). they should be closed beforehand. 

because now the recovery is executed from the connections on the pool, there can be more pressure on the number of available connections. (or can be an issue too, of course)

**Comment by barreiro** [comment]
I'll have a look at the test case later today.

**Comment by graben** [comment]
A last fact I found. It seems it has to deal with `ConnectionPool.localCache` variable. First recovery round localCache is null, and the pool gets completely flushed (closing all connections). Second round localCache is filled and everything is fine.

Hope that helps a bit :-/

**Comment by graben** [comment]
@barreiro : I just did a little "dirty" experiment. Instead of calling `handler.transactionEnd();` in `XAConnectionWrapper.close()` I called `handler.setFlushOnly();` to force connection to get removed from pool. After that, the recovery process gets finished immediately. IHMO it looks like a connection used by recovery process couldn't been brought back to pool this way. Maybe some internal state gets wrong or something needs to be refreshed?

**Comment by graben** [comment]
Doing a `rollback()` on `rawConnection()` just before calling `handler.transactionEnd();` works, too. Might be an issue with h2 that doing recovery with the same connection that is used in between the application is causing no data transfer afterwards. But as far as I know, most JDBC drivers are working the same way. Maybe rolling back is a proper solution?!

**Review by cunningt — APPROVED** [review]

**Pull request merged**
