### PR TITLE
Update Camel to 4.0.4

### PR DESCRIPTION
**Pull request by graben**

### CODE REVIEW

**Review by cunningt — APPROVED** [review]
Looks good to me!

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Unfortunately this now has a conflict, can you please rebase?

Thanks

**Comment by graben** [comment]
@geoand: Branch is rebased

**Comment by geoand** [comment]
Thanks!

**Review by geoand — APPROVED** [review]

**Pull request merged**
