### PR TITLE
Upgrade Spring Boot to 2.4.9

### PR DESCRIPTION
**Pull request by graben**

### CODE REVIEW

**Comment by cmoulliard** [comment]
@gytis Do you agree to bump the version of the SB ?

**Comment by graben** [comment]
@cmoulliard , @gytis: I will bump this PR to the newest version 2.4.10

**Comment by jacobdotcosta** [comment]
Could we keep an intermediary release with Spring Boot `2.4.9` before bumping to `2.4.10`?

**Comment by graben** [comment]
> Could we keep an intermediary release with Spring Boot `2.4.9` before bumping to `2.4.10`?

Fine with me, if someone can update and release, since @gytis seems to be absent at the moment.

**Review by aureamunoz — APPROVED** [review]
LGTM

**Pull request merged**
