### PR TITLE
Update Narayana to 7.0.0.Final

### PR DESCRIPTION
**Pull request by graben**

### CODE REVIEW

**Comment by cmoulliard** [comment]
Can you fix the conflict please ? @graben

**Comment by graben** [comment]
@cmoulliard : Conflict is fixed.

**Review by cunningt — APPROVED** [review]

**Comment by cmoulliard** [comment]
Conflict is still there !

**Comment by graben** [comment]
Oh no, it appears again after merge of last PR. I'll fix it this evening.

**Comment by graben** [comment]
@cmoulliard : Fixed once again ;)

**Review by cmoulliard — APPROVED** [review]

**Pull request merged**
